### ISSUE TITLE
Consider adding support for exported bindings

### ISSUE THREAD

**Issue by ZauberNerd** [KnisterPeter/paeckchen#58]
ES2015 modules export bindings (pointers to the value) instead of copies of the values themselves.
http://www.2ality.com/2015/07/es6-module-exports.html
[Here is an example how Babel handles this](http://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Cstage-2&experimental=true&loose=true&spec=false&code=let%20i%20%3D%200%3B%0Aconst%20increment%20%3D%20%28%29%20%3D%3E%20%7B%20i%2B%2B%3B%20%7D%3B%0A%0Aexport%20%7B%20i%2C%20increment%20%7D%3B) and an example of how immutable values are handled [If the value is not being mutated it is exported as copy](http://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Cstage-2&experimental=true&loose=true&spec=false&code=let%20i%20%3D%200%3B%0Aconst%20increment%20%3D%20%28%29%20%3D%3E%20%7B%20i%3B%20%7D%3B%0A%0Aexport%20%7B%20i%2C%20increment%20%7D%3B)
Do we want to follow this? If not I think we should make a note of it somewhere.
If we don't want to check the entire file if the variable is being mutated, I think we could also export ES5 getters which just return a reference to the value.

**Comment by KnisterPeter** [comment]
I would like to support it but not at expense of performance. Too much AST visits cost a lot of performance and since most code currently isn't designed to support bindings (commonjs doesn't know this) we are currently realtiv safe by assuming not to use bindings.
This reasoning has some shortcommings and will need to be addressed in future. So we should keep this open and work on it when paeckchen is feature complete I think.

**Comment by ZauberNerd** [comment]
Sounds good to me. Just wanted to bring this to attention as it might be a source of bugs ;)
