### ISSUE TITLE
Configuration: Specify file extensions in configuration

### ISSUE THREAD

**Issue by ZauberNerd** [KnisterPeter/paeckchen#93]
When using paeckchen to bundle itself, it fails because some modules do `require('./package.json')` which causes the acorn parser to fail.
We should add a configuration option for file extensions and default it to `.js`.

**Comment by marionebl** [comment]
I'd argue we should emulate the default `require` behavior and import json files as implicit `module.exports = JSON.parse(fs.readFileSync(filePath, 'utf-8'))`.

**Comment by KnisterPeter** [comment]
I would like to allow both, but for different reasons. This are two different concerens.
File extensions should be configurable, because we don't know what name or extensions a project uses.

Regarding the json files, IMHO we should include the read JSON code into a module 'import' that virtual module. That would mimic the require behaviour (could be done in a commonjs plugin) of commonjs but without indirectly introduce an fs dependency.
